### ISSUE TITLE
Question to protein language model

### ISSUE THREAD

**Issue by wangleiofficial** [tttianhao/CLEAN#5] opened 2023-03-31 03:11 UTC
Hi, congratulations！protein language models have played a key role in the protein feature extraction. Since none of the methods you compared use a language model, is that the main reason your method is good. I think supervised contrastive learning should not be so different from supervised learning. Our lab has also developed a lightweight protein language model (ProtFlash), and we would like to collaborate to test this approach if given the opportunity.

**Comment by tttianhao** [comment] 2023-03-31 14:47
Hi, let's continue our discussion through email. Since the issue is not code related, I'm closing the issue for now.

**Closed by tttianhao** 2023-03-31 14:47 UTC
